### PR TITLE
Added support for Redbelly Chain Network

### PR DESCRIPTION
**Pull request by sherrys808**
Updated Constants to add support for Redbelly Network.

### CODE REVIEW

**Comment by vmidyllic** [comment]
see here https://github.com/iden3/js-iden3-core/pull/26#issuecomment-1787235711

**Comment by Aastha9018** [comment]
> see here [#26 (comment)](https://github.com/iden3/js-iden3-core/pull/26#issuecomment-1787235711) and [#25 (comment)](https://github.com/iden3/js-iden3-core/pull/25#issuecomment-1761498358)
> 
> If you still consider that you network should be supported by our team on each level you can contact @OBrezhniev to have further discussions

Hey @vmidyllic thanks for your comment. I do have a follow up question though, after the [PR 26](https://github.com/iden3/js-iden3-core/pull/26) gets merged so will we be able to use the Polygon flutter sdk by passign our chain and network names in the configuration or will that need any more changes?

**Comment by vmidyllic** [comment]
not after this particular PR is merged. In @0xpolygonid/js-sdk it will be possible for sure after it. 
In flutter, same changes will be also needed, but in the end result  - it should be possible to you dynamic methods and network on flutter-sdk as well.

**Comment by Aastha9018** [comment]
> not after this particular PR is merged. In @0xpolygonid/js-sdk it will be possible for sure after it. In flutter, same changes will be also needed, but in the end result - it should be possible to you dynamic methods and network on flutter-sdk as well.

Thanks for the reply, is there any progress on https://github.com/iden3/js-iden3-core/pull/26

**Pull request closed without merging**
